"""Add store_id, featured_store, featured_mall columns to products

Revision ID: 44ac423f8419
Revises: d323bade5881
Create Date: 2021-11-17 16:00:02.839974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44ac423f8419'
down_revision = 'd323bade5881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('store_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('featured_store', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('featured_mall', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'products', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'featured_mall')
    op.drop_column('products', 'featured_store')
    op.drop_column('products', 'store_id')
    # ### end Alembic commands ###
